//this file contains all the various actionTypes

/**
 * Redux constants module
 * @module Redux-contants
 */

/**
 * @file actionType.js file contains all the various actionTypes
 * @author Vibhor
 */

/**
 * Action Types
 * @type {Object}
 */
const actionType = {
  TOGGLE_SAFE_MODE: "TOGGLE_SAFE_MODE",

  ADD_CHANNEL_ID_LINK_OPENER: "ADD_CHANNEL_ID_LINK_OPENER",
  REMOVE_CHANNEL_ID_LINK_OPENER: "REMOVE_CHANNEL_ID_LINK_OPENER",
  TOGGLE_LINK_OPENER: "TOGGLE_LINK_OPENER",

  ADD_CHANNEL_ID_INVITE_JOINER: "ADD_CHANNEL_ID_INVITE_JOINER",
  REMOVE_CHANNEL_ID_INVITE_JOINER: "REMOVE_CHANNEL_ID_INVITE_JOINER",
  TOGGLE_INVITE_JOINER: "TOGGLE_INVITE_JOINER",

  KEYWORD_TWITTER: "KEYWORD_TWITTER",
  DELETE_KEYWORD_TWITTER: "DELETE_KEYWORD_TWITTER",
  ADD_USER_TWITTER: "ADD_USER_TWITTER",
  DELETE_USER_TWITTER: "DELETE_USER_TWITTER",
  KEYWORD_DISCORD: "KEYWORD_DISCORD",
  SET_DELAY: "SET_DELAY",
  HANDLE_CHECKBOX: "HANDLE_CHECKBOX",
  SET_URL_APPENDER: "SET_URL_APPENDER",
  TOGGLE_URL_APPENDER: "TOGGLE_URL_APPENDER",
  ADD_SETTINGS_KEYS: "ADD_SETTINGS_KEYS",
  ADD_CLAIMER_TOKEN: "ADD_CLAIMER_TOKEN",
  SETTING_ADD_WEBHOOK: "SETTING_ADD_WEBHOOK",
  SETTING_REMOVE_WEBHOOK: "SETTING_REMOVE_WEBHOOK",
  SETTING_ADD_CHROMEUSER: "SETTING_ADD_CHROMEUSER",
  SETTING_REMOVE_CHROMEUSER: "SETTING_REMOVE_CHROMEUSER",
  SETTING_EDIT_CHROMEUSER: "SETTING_EDIT_CHROMEUSER",
  FETCH_TWEETS: "FETCH_TWEETS",
  STORE_TWEET_INFO: "STORE_TWEET_INFO",
  ADD_FEATURED_TWEET: "ADD_FEATURED_TWEET",
  CLEAR_LATEST_TWEETS: "CLEAR_LATEST_TWEETS",
  CLEAR_FEATURED_TWEETS: "CLEAR_FEATURED_TWEETS",
  TOGGLE_SWITCH_BUTTON: "TOGGLE_SWITCH_BUTTON",
  SET_TIMER: "SET_TIMER",
  TOGGLE_JOINER: "TOGGLE_JOINER",
  TOGGLE_OPENER: "TOGGLE_OPENER",

  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  EDIT_ACCOUNT: "EDIT_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",

  SET_WEBHOOK: "SET_WEBHOOK",
  TOGGLE_BUTTONS_WEBHOOK: "TOGGLE_BUTTONS_WEBHOOK",
  SET_BACKGROUND_ANIMATION: "SET_BACKGROUND_ANIMATION",

  CREATE_CHROME_USER_DISCORD: "CREATE_CHROME_USER_DISCORD",
  DELETE_CHROME_USER_DISCORD: "DELETE_CHROME_USER_DISCORD",
  SELECT_CHROME_PROFILE: "SELECT_CHROME_PROFILE",
  UNSELECT_CHROME_PROFILE: "UNSELECT_CHROME_PROFILE",

  SELECT_MONITOR_TOKEN_LO: "SELECT_MONITOR_TOKEN_LO",
  SELECT_MONITOR_TOKEN_IJ: "SELECT_MONITOR_TOKEN_IJ",
  SELECT_CLAIMER_TOKEN_IJ: "SELECT_CLAIMER_TOKEN_IJ",

  ADD_TO_LOGS: "ADD_TO_LOGS",
  CLEAR_LOGS: "CLEAR_LOGS",
  TOGGLE_LOADING: "TOGGLE_LOADING",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",

  SHOW_USER_PROFILE: "SHOW_USER_PROFILE",
  ADD_CHANNEL_NAME: "ADD_CHANNEL_NAME",
};
export default actionType;
